### ISSUE TITLE
What will happen on a fork?

### ISSUE THREAD

**Issue by i-am-the-slime** [ethercrow/lightstep-haskell#29]
Since there's a stack per thread-id will there be a problem when forking a thread and then creating child spans in the forked thread? How do you handle this?

**Comment by ethercrow** [comment]
In this situation the user code has to propagate the tracing context via `currentSpanContext` and `setParentSpanContext`. There is an example in the readme, look for "Parallel map reduce".

**Comment by i-am-the-slime** [comment]
Lovely, thank you!
